#!/usr/bin/perl -w

use Socket;
use strict;

my $FQDN = `hostname`;
chomp $FQDN;
system("cp -f /var/lib/puppet/firstboot/resolv.conf /etc/resolv.conf");

my $DONE = 0;
my $address;
while (!$DONE ) {

  if ( ! ($FQDN =~ /truecarcorp.com$/ or $FQDN =~ /qwest.zag.com$/) ) {
     print "ERROR: $FQDN does not have truecarcorp.com or qwest.zag.com in the hostname.";
     exit -1;
    };

  my $n = inet_aton($FQDN) or die "ERROR Could not resolve $FQDN.  Try again";

  $address = inet_ntoa($n) ;

  if ($address =~ /^[10\.|172\.|66\.172\.31]/) { $DONE = 1; }
  else { print "IP address ($address) is out of range  Try again\n"; exit 2; }
}

system("echo \"z_nodename=$FQDN\" > /etc/facts");
system("hostname $FQDN");

my $puppet_ping = `/usr/sbin/fping puppet`;
if ( ! ($puppet_ping =~ "puppet is alive")) {
  print "puppet isn't pingable. did you remember the default gw? route add default gw $address\n";
  exit -1;
}

system("puppet agent --test --fqdn=$FQDN");
system("puppet agent --test --fqdn=$FQDN");
system("puppet agent --test --fqdn=$FQDN");
system("puppet agent --test --fqdn=$FQDN");
system("rm -rvf /root/.bash_history");
system("rm -vf /var/log/*");
system("rm -vf /var/log/*/*");
system("rm -vf /etc/rc3.d/S11firstboot");
system("reboot");
